### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by adamhalasz** [Nosthertus/diet-static-stream#8]
I get this error with a pretty basic diet server serving a single `style.css` file from an `index.html`. I actually get the error even if I don't serve the `style.css`. The error is gone if I don't load diet-static as a footer middleware. 

Any suggestions why? 

```
Error: write after end
    at ServerResponse.write (_http_outgoing.js:11:10)
    at ReadStream.ondata (_stream_readable.js:11:10)
    at emitOne (events.js:11:10)
    at ReadStream.emit (events.js:11:3)
    at readableAddChunk (_stream_readable.js:11:10)
    at ReadStream.Readable.push (_stream_readable.js:11:10)
    at onread (fs.js:11:10)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:11:10)
```

- Diet version: 0.15.0
- Node version: v7.9.0
- Diet Static Stream version: 1.1.0
- OS: Ubuntu v16.0.4

**Comment by adamhalasz** [comment]
Ok I just figured if I load `diet-static-stream` with `app.header()` the error is gone.

```js
var static = require("diet-static-stream")({
    path: "views"
});
app.header(static);
```

Is there a reason for this to be a footer middleware?

**Comment by oscarr-reyes** [comment]
greetings, can you show me the code you used?.. i have read something about response states in `node` and i think this might be related
